/**
 * @file migrate.ts
 * @description Applies the bundled Drizzle migrations to the on-device database
 * using `useMigrations` from the expo-sqlite migrator. The bundled
 * `drizzle/migrations.js` is generated by `drizzle-kit` (driver: 'expo') and
 * imports each `.sql` migration as an inline string.
 *
 * The hook must be called with a fully opened database — the `DatabaseProvider`
 * only mounts the inner component (and therefore this hook) once `getDb()` has
 * resolved, so the hook is never invoked with a null db.
 */
import { useMigrations } from "drizzle-orm/expo-sqlite/migrator";
import migrations from "../../drizzle/migrations";
import type { Database } from "./client";

export interface MigrationState {
  success: boolean;
  error?: Error;
}

/**
 * Applies Drizzle migrations against the opened database. Returns a stable
 * `{ success, error }` state that flips to success once every pending migration
 * has run (idempotent across restarts — Drizzle tracks applied migrations in
 * its own `__drizzle_migrations` journal).
 *
 * @param db - The initialized Drizzle database instance (must be non-null)
 */
export function useDatabaseMigrations(db: Database): MigrationState {
  return useMigrations(db, migrations);
}