/**
 * @file syncStore.tsx
 * @description Orchestrates the offline-first synchronization engine.
 * It tracks network connectivity, manages the background syncing state,
 * and handles the batch uploading of queued quiz results to Supabase.
 */
import React, { useEffect, useCallback } from "react";
import { create } from "zustand";
import { useQueryClient, onlineManager } from "@tanstack/react-query";
import NetInfo, { NetInfoState } from "@react-native-community/netinfo";
import { useAuth } from "./authStore";
import {
  getFlushableForUser,
  pendingCount as getPendingCount,
  recordFailure,
  removeSynced,
  MAX_SYNC_ATTEMPTS,
} from "@/src/shared/services/offlineQueue";
import { supabase } from "@/src/shared/services/supabase";
import { isDeviceOnline } from "@/src/shared/utils/netInfo";

/**
 * Module-level flush guard + backoff clock — shared by every `useSyncActions()`
 * instance so only ONE flush loop can run at a time app-wide (audit P2-9).
 * Previously these were per-instance `useRef`s, letting SyncProvider and each
 * quiz session run concurrent flush loops.
 */
let flushing = false;
let lastFlushTime = 0;

/**
 * Interface representing the global synchronization state.
 */
interface SyncState {
  isOnline: boolean;
  isSyncing: boolean;
  pendingCount: number;
  setIsOnline: (online: boolean) => void;
  setIsSyncing: (syncing: boolean) => void;
  setPendingCount: (count: number) => void;
}

/**
 * Zustand store for managing global synchronization UI state.
 * Used by components to display "Offline" banners or "Syncing..." indicators.
 */
export const useSyncStore = create<SyncState>((set) => ({
  isOnline: true,
  isSyncing: false,
  pendingCount: 0,
  setIsOnline: (online) => set({ isOnline: online }),
  setIsSyncing: (syncing) => set({ isSyncing: syncing }),
  setPendingCount: (count) => set({ pendingCount: count }),
}));

/**
 * Custom hook providing actions to interact with the sync engine.
 * 
 * @returns An object containing `refreshCount` to update the pending UI badge,
 * and `flush` to manually or automatically trigger a queue upload.
 */
export function useSyncActions() {
  const queryClient = useQueryClient();
  const user = useAuth((s) => s.user);
  const setPendingCount = useSyncStore((s) => s.setPendingCount);
  const setIsSyncing = useSyncStore((s) => s.setIsSyncing);

  /**
   * Updates the global pending count based on the current user's offline queue.
   */
  const refreshCount = useCallback(async () => {
    const n = await getPendingCount(user?.id);
    setPendingCount(n);
  }, [user, setPendingCount]);

  /**
   * Flushes the offline queue by sequentially uploading pending results to Supabase.
   * - Implements a 30-second backoff upon network/timeout failures.
   * - Uses `Promise.race` for a strict 10s per-item timeout.
   * - Handles Postgres duplicate/conflict errors gracefully (e.g., 23505).
   * - Dead-letters per-item failures: a rejected item increments its failure
   *   counter and the loop CONTINUES, so one bad row can never block the rest
   *   of the queue. Items past `MAX_SYNC_ATTEMPTS` are excluded from future
   *   flushes (audit P1-2).
   */
  const flush = useCallback(async () => {
    if (flushing || !user) return;

    // Basic backoff: skip if we failed a flush in the last 30 seconds
    const now = Date.now();
    if (now - lastFlushTime < 30000) return;

    const queue = await getFlushableForUser(user.id, MAX_SYNC_ATTEMPTS);
    if (queue.length === 0) {
      await refreshCount();
      return;
    }

    flushing = true;
    setIsSyncing(true);

    let anySynced = false;
    const syncedIds: string[] = [];

    try {
      for (const item of queue) {
        // Legacy items generated by Date.now()-Math.random() contain a '.'
        // If we send them as `id` to Supabase, Postgres throws 22P02 and they get deleted without syncing.
        const isLegacy = item.localId.includes(".");

        const payload: Record<string, unknown> = {
          user_id: item.userId,
          lecture_id: item.lectureId,
          score: item.score,
          total_questions: item.totalQuestions,
          correct_answers: item.correctAnswers,
          created_at: item.createdAt,
        };

        if (!isLegacy) {
          payload["id"] = item.localId;
        }

        const insertPromise = supabase.from("quiz_results").insert(payload);

        // 10s timeout
        const timeoutPromise = new Promise<{ error: { code?: string } | null }>(
          (_, reject) => setTimeout(() => reject(new Error("timeout")), 10000),
        );

        const { error } = await Promise.race([insertPromise, timeoutPromise]);

        if (!error) {
          syncedIds.push(item.localId);
          anySynced = true;
        } else {
          if (__DEV__)
            console.error(
              `[useSyncSession] flush insert FAILED for item ${item.localId}:`,
              error,
            );
          if (error.code === "23505") {
            // Row already exists on server (duplicate) — safe to remove from local queue
            syncedIds.push(item.localId);
            anySynced = true;
          } else {
            // Server rejected this item (invalid FK, RLS, schema mismatch…).
            // Record the failure and keep flushing the rest — never break.
            await recordFailure([item.localId]);
          }
        }
      }

      if (syncedIds.length > 0) await removeSynced(syncedIds);
      if (anySynced) {
        queryClient.invalidateQueries({ queryKey: ["stats"] });
        queryClient.invalidateQueries({ queryKey: ["progress_sync"] });
      }
    } catch (err) {
      // Catch timeouts from Promise.race — a network-wide failure, so back off.
      lastFlushTime = Date.now();
    } finally {
      await refreshCount();
      setIsSyncing(false);
      flushing = false;
    }
  }, [user, queryClient, refreshCount, setIsSyncing]);

  return { refreshCount, flush };
}

/**
 * Global provider that mounts the network listeners and orchestration logic.
 * It bridges `NetInfo` with React Query's `onlineManager`, and automatically 
 * triggers a queue flush when the device comes back online.
 * 
 * Should be mounted high in the React tree (e.g., inside `_layout.tsx`).
 */
export function SyncProvider({ children }: { children: React.ReactNode }) {
  const isOnline = useSyncStore((s) => s.isOnline);
  const setIsOnline = useSyncStore((s) => s.setIsOnline);
  const user = useAuth((s) => s.user);
  const { refreshCount, flush } = useSyncActions();

  useEffect(() => {
    // Sync initial state
    NetInfo.fetch().then((state: NetInfoState) => {
      const online = isDeviceOnline(state);
      setIsOnline(online);
      onlineManager.setOnline(online);
    });

    // Subscribe to changes
    const unsubscribe = NetInfo.addEventListener((state: NetInfoState) => {
      const online = isDeviceOnline(state);
      setIsOnline(online);
      onlineManager.setOnline(online);
    });

    return unsubscribe;
  }, [setIsOnline]);

  useEffect(() => {
    refreshCount();
    if (isOnline && user) flush();
  }, [isOnline, user, flush, refreshCount]);

  return <>{children}</>;
}
