import React, { useEffect, useCallback, useRef } from "react";
import { create } from "zustand";
import { useQueryClient, onlineManager } from "@tanstack/react-query";
import NetInfo, { NetInfoState } from "@react-native-community/netinfo";
import { useAuth } from "./authStore";
import { getQueue, pendingCount as getPendingCount, removeSynced } from "@/src/shared/services/offlineQueue";
import { supabase } from "@/src/shared/services/supabase";

interface SyncState {
  isOnline: boolean;
  isSyncing: boolean;
  pendingCount: number;
  setIsOnline: (online: boolean) => void;
  setIsSyncing: (syncing: boolean) => void;
  setPendingCount: (count: number) => void;
}

export const useSyncStore = create<SyncState>((set) => ({
  isOnline: true,
  isSyncing: false,
  pendingCount: 0,
  setIsOnline: (online) => set({ isOnline: online }),
  setIsSyncing: (syncing) => set({ isSyncing: syncing }),
  setPendingCount: (count) => set({ pendingCount: count }),
}));

export function useSyncActions() {
  const queryClient = useQueryClient();
  const user = useAuth((s) => s.user);
  const setPendingCount = useSyncStore(s => s.setPendingCount);
  const setIsSyncing = useSyncStore(s => s.setIsSyncing);
  const flushing = useRef(false);
  const lastFlushTime = useRef<number>(0);

  const refreshCount = useCallback(async () => {
    const n = await getPendingCount(user?.id);
    setPendingCount(n);
  }, [user, setPendingCount]);

  const flush = useCallback(async () => {
    if (flushing.current || !user) return;
    
    // Basic backoff: skip if we failed a flush in the last 30 seconds
    const now = Date.now();
    if (now - lastFlushTime.current < 30000) return;

    const fullQueue = await getQueue();
    const queue = fullQueue.filter((item) => item.userId === user.id);
    if (queue.length === 0) {
      await refreshCount();
      return;
    }

    flushing.current = true;
    setIsSyncing(true);

    let anySynced = false;
    const syncedIds: string[] = [];

    try {
      for (const item of queue) {
        // Legacy items generated by Date.now()-Math.random() contain a '.'
        // If we send them as `id` to Supabase, Postgres throws 22P02 and they get deleted without syncing.
        const isLegacy = item.localId.includes(".");

        const payload: any = {
          user_id: item.userId,
          lecture_id: item.lectureId,
          score: item.score,
          total_questions: item.totalQuestions,
          correct_answers: item.correctAnswers,
          created_at: item.createdAt,
        };

        if (!isLegacy) {
          payload.id = item.localId;
        }

        const insertPromise = supabase.from("quiz_results").insert(payload);

        // 10s timeout
        const timeoutPromise = new Promise<{ error: any }>((_, reject) => 
          setTimeout(() => reject(new Error("timeout")), 10000)
        );

        const { error } = await Promise.race([insertPromise, timeoutPromise]);

        if (!error) {
          syncedIds.push(item.localId);
          anySynced = true;
        } else {
          if (__DEV__) console.error(`[useSyncSession] flush insert FAILED for item ${item.localId}:`, error);
          if (error.code && (error.code.startsWith("23") || error.code.startsWith("42") || error.code.startsWith("22"))) {
            syncedIds.push(item.localId);
            anySynced = true; // The row already exists (duplicate), so force UI to fetch updated server stats
          } else {
            // Network error or timeout. Bail out of loop.
            lastFlushTime.current = Date.now();
            break;
          }
        }
      }

      if (syncedIds.length > 0) await removeSynced(syncedIds);
      if (anySynced) {
        queryClient.invalidateQueries({ queryKey: ["stats"] });
        queryClient.invalidateQueries({ queryKey: ["progress"] });
      }
    } catch (err) {
      // Catch timeouts from Promise.race
      lastFlushTime.current = Date.now();
    } finally {
      await refreshCount();
      setIsSyncing(false);
      flushing.current = false;
    }
  }, [user, queryClient, refreshCount, setIsSyncing]);

  return { refreshCount, flush };
}

export function SyncProvider({ children }: { children: React.ReactNode }) {
  const isOnline = useSyncStore((s) => s.isOnline);
  const setIsOnline = useSyncStore((s) => s.setIsOnline);
  const user = useAuth((s) => s.user);
  const { refreshCount, flush } = useSyncActions();

  useEffect(() => {
    // Sync initial state
    NetInfo.fetch().then((state: NetInfoState) => {
      const online = state.isConnected !== false && state.isInternetReachable !== false;
      setIsOnline(online);
      onlineManager.setOnline(online);
    });

    // Subscribe to changes
    const unsubscribe = NetInfo.addEventListener((state: NetInfoState) => {
      const online = state.isConnected !== false && state.isInternetReachable !== false;
      setIsOnline(online);
      onlineManager.setOnline(online);
    });

    return unsubscribe;
  }, [setIsOnline]);

  useEffect(() => {
    refreshCount();
    if (isOnline && user) flush();
  }, [isOnline, user, flush, refreshCount]);

  return <>{children}</>;
}


