/**
 * Pure renderers for archgovern: markdown architecture doc, mermaid charts
 * doc, the interactive HTML (template substitution), and the CLI governance
 * report. Plus the exit-code computation.
 */

const fs = require("fs");
const path = require("path");

const ENGINE_NAME = "archgovern";

// Shared layering order for both renderers: emit sections in `orderedLayers`
// order, then surplus layers (e.g. unknown) as a final bucket.
function orderNodes(nodes, orderedLayers) {
  const layers = orderedLayers || ["presentation", "application", "infrastructure", "external"];
  const nodesByLayer = {};
  nodes.forEach((n) => {
    const l = n.layer || "unknown";
    if (!nodesByLayer[l]) nodesByLayer[l] = [];
    nodesByLayer[l].push(n);
  });

  const sections = [];
  const renderedLayers = new Set();
  for (const layer of layers) {
    const nodesInLayer = nodesByLayer[layer] || [];
    if (nodesInLayer.length === 0) continue;
    renderedLayers.add(layer);
    sections.push({ layer, nodes: nodesInLayer });
  }

  const leftoverNodes = [];
  for (const [layer, nodesInLayer] of Object.entries(nodesByLayer)) {
    if (!renderedLayers.has(layer)) leftoverNodes.push(...nodesInLayer);
  }

  return { layers, nodesByLayer, sections, leftoverNodes };
}

function renderArchitectureMd(nodes, flows, orderedLayers, projectName) {
  const title = projectName ? `${projectName} Architecture` : "Architecture";
  let mdContent = `# ${title}

> **Note to AI Agents**: This file is auto-generated by the governance engine (\`${ENGINE_NAME}\`). Nodes, edges, and layers are derived directly from the codebase via comment-safe import extraction, CommonJS/ESM barrel tracing, and tsconfig path aliases; curated prose is linted against known-stale terms; flows are validated against the graph; and the build fails on any drift (strict mode can additionally fail on imported local files missing from the graph). Use this to understand the structure, layers, and flows of the application.

`;

  const { sections, leftoverNodes } = orderNodes(nodes, orderedLayers);

  mdContent += `## 📦 Nodes (Components, Services, & State)\n\n`;

  sections.forEach(({ layer, nodes: nodesInLayer }) => {
    mdContent += `### ${layer.toUpperCase()} LAYER\n\n`;
    nodesInLayer.forEach((n) => {
      mdContent += `- **${n.id}** (${n.technology || "Unknown"}): ${n.description}\n`;
    });
    mdContent += "\n";
  });

  if (leftoverNodes.length > 0) {
    mdContent += `### OTHER LAYER\n\n`;
    leftoverNodes.forEach((n) => {
      mdContent += `- **${n.id}** (${n.technology || "Unknown"}): ${n.description}\n`;
    });
    mdContent += "\n";
  }

  mdContent += `## 🔄 Flows (User Journeys & Sequences)\n\n`;
  flows.forEach((flow) => {
    mdContent += `### ${flow.name}\n${flow.description}\n\n`;
    if (flow.steps && flow.steps.length > 0) {
      [...flow.steps]
        .sort((a, b) => a.order - b.order)
        .forEach((step) => {
          mdContent += `${step.order}. **${step.node}**: ${step.action}\n`;
        });
      mdContent += "\n";
    }
  });

  return mdContent;
}

function renderChartsMd(nodes, archEdges, orderedLayers, layerClasses, projectName) {
  const title = projectName ? `${projectName} Architecture` : "Architecture";
  let chartsMdContent = `# ${title} Charts

> **Note to AI Agents**: This file is auto-generated by the governance engine (\`${ENGINE_NAME}\`).

## 📊 Architecture Diagram

\`\`\`mermaid
flowchart LR

  %% Styling Classes
`;

  const layers = orderedLayers || ["presentation", "application", "infrastructure", "external"];
  const classes = layerClasses || {};

  for (const layer of layers) {
    if (classes[layer]) {
      chartsMdContent += `  classDef ${layer} ${classes[layer]}\n`;
    }
  }

  const { sections, leftoverNodes } = orderNodes(nodes, orderedLayers);

  sections.forEach(({ layer, nodes: nodesInLayer }) => {
    chartsMdContent += `  subgraph ${layer.toUpperCase()}\n`;
    chartsMdContent += `    direction TB\n`;
    nodesInLayer.forEach((n) => {
      chartsMdContent += `    ${n.id}["${n.label}"]:::${layer}\n`;
    });
    chartsMdContent += `  end\n\n`;
  });

  if (leftoverNodes.length > 0) {
    const unknownClass =
      classes.unknown || "fill:#666,stroke:#999,stroke-width:1px,stroke-dasharray: 5 5";
    chartsMdContent += `  classDef unknown ${unknownClass}\n\n`;
    chartsMdContent += `  subgraph MISC\n`;
    chartsMdContent += `    direction TB\n`;
    leftoverNodes.forEach((n) => {
      chartsMdContent += `    ${n.id}["${n.label}"]:::unknown\n`;
    });
    chartsMdContent += `  end\n\n`;
  }

  archEdges.forEach((e) => {
    chartsMdContent += `  ${e.source} --> ${e.target}\n`;
  });
  chartsMdContent += "```\n\n";

  return chartsMdContent;
}

// Render the interactive HTML by substituting the template placeholder.
function renderHtml(architecture, templatePath) {
  if (!templatePath || !fs.existsSync(templatePath)) return null;
  let htmlContent = fs.readFileSync(templatePath, "utf8");
  htmlContent = htmlContent.replace(
    "__ARCHITECTURE_JSON__",
    JSON.stringify(architecture),
  );
  htmlContent = htmlContent.replace("__ARCHITECTURE_TITLE__", "Architecture Graph");
  return htmlContent;
}

function renderReport(result) {
  let report = "";

  report += "\n╔══════════════════════════════════════════════════════════╗\n";
  report += "║           ARCHITECTURE GOVERNANCE REPORT                ║\n";
  report += "╚══════════════════════════════════════════════════════════╝\n\n";

  // — Stale paths —
  if (result.stalePatterns.length > 0) {
    report += "⚠️  STALE PATHS REMOVED FROM NODE MAPPING:\n";
    result.stalePatterns.forEach((s) => {
      report += `   ❌ ${s.nodeId} → ${s.pattern}\n`;
    });
    report += "\n";
  }

  if (result.staleMetadataPaths && result.staleMetadataPaths.length > 0) {
    report += "⚠️  STALE NODE METADATA PATHS CORRECTED:\n";
    result.staleMetadataPaths.forEach((s) => {
      report += `   ❌ ${s.nodeId}: "${s.curatedPath}" -> "${s.derivedPath}"\n`;
    });
    report += "\n";
  }

  // — Node report —
  const oldNodeIds = new Set(result.existingNodes.map((n) => n.id));
  const newNodeIds = result.allNodeIds;
  const keptNodes = [...newNodeIds].filter((id) => oldNodeIds.has(id));

  report += `📦 NODES: ${newNodeIds.size} total\n`;
  report += `   ✅ Verified: ${keptNodes.length}\n`;
  keptNodes.forEach((n) => {
    const fileCount = result.nodeToFiles.get(n)?.length || 0;
    const label = fileCount > 0 ? `(${fileCount} files)` : "(external)";
    report += `      • ${n} ${label}\n`;
  });

  if (result.addedNodes.length > 0) {
    report += `   ➕ Added: ${result.addedNodes.length}\n`;
    result.addedNodes.forEach((n) => (report += `      • ${n}\n`));
  }
  if (result.removedNodes.length > 0) {
    report += `   ❌ Removed: ${result.removedNodes.length}\n`;
    result.removedNodes.forEach((n) => (report += `      • ${n}\n`));
  }
  report += "\n";

  // — Edge report —
  const oldEdgeKeys = new Set(
    result.existingEdges.filter((e) => e.id).map((e) => `${e.source}->${e.target}`),
  );
  const newEdgeKeys = new Set(result.verifiedArchEdges.map((e) => `${e.source}->${e.target}`));
  const keptEdges = [...newEdgeKeys].filter((k) => oldEdgeKeys.has(k));

  report += `🔗 ARCHITECTURAL EDGES: ${newEdgeKeys.size} total\n`;
  report += `   ✅ Verified: ${keptEdges.length}\n`;
  if (result.addedEdges.length > 0) {
    report += `   ➕ Added: ${result.addedEdges.length}\n`;
    result.addedEdges.forEach((e) => {
      const evidence = result.edgeEvidence.get(e) || [];
      const files = evidence
        .map((ev) => ev.file)
        .slice(0, 3)
        .join(", ");
      report += `      • ${e}  [${files}]\n`;
    });
  }
  if (result.removedEdges.length > 0) {
    report += `   ❌ Phantom edges removed: ${result.removedEdges.length}\n`;
    result.removedEdges.forEach((e) => (report += `      • ${e}  (no import found in code)\n`));
  }
  report += "\n";

  // — Flow trigger edges —
  const removedFlowTriggers =
    result.existingFlowTriggerEdges.length - result.verifiedFlowEdges.length;
  report += `🔄 FLOW TRIGGER EDGES: ${result.verifiedFlowEdges.length} kept\n`;
  if (removedFlowTriggers > 0) {
    report += `   ❌ ${removedFlowTriggers} removed (referenced non-existent nodes)\n`;
  }
  report += "\n";

  // — Unmapped imports (advisory unless strictUnmappedLocal) —
  const droppedImports = result.droppedImports || [];
  if (droppedImports.length > 0) {
    const verbose = result.verbose === true;
    report += `⚠️ UNMAPPED IMPORTS: ${droppedImports.length} (advisory)\n`;
    const samples = verbose ? droppedImports : droppedImports.slice(0, 5);
    samples.forEach((d) => {
      report += `   • ${d.fromNode} -> ${d.targetPath} [${d.reason}]\n`;
    });
    if (!verbose && droppedImports.length > 5) {
      report += `   ... and ${droppedImports.length - 5} more (run with --verbose to list all)\n`;
    }
    report += "\n";
  }

  // — Strict local-unmapped (build failure) —
  const unmappedLocalImports = result.unmappedLocalImports || [];
  if (unmappedLocalImports.length > 0) {
    report += `🚫 STRICT: LOCAL FILES IMPORTED BUT NOT IN THE GRAPH: ${unmappedLocalImports.length}\n`;
    report += "   strictUnmappedLocal is on — the graph is incomplete. Map these files in nodeMapping:\n";
    unmappedLocalImports.slice(0, 10).forEach((d) => {
      report += `   • ${d.targetPath}  (imported by ${d.fromNode})\n`;
    });
    if (unmappedLocalImports.length > 10) {
      report += `   ... and ${unmappedLocalImports.length - 10} more\n`;
    }
    report += "\n";
  }

  // — Flow validation —
  if (result.flowWarnings.length > 0) {
    report += "⚠️  FLOW VALIDATION WARNINGS:\n";
    result.flowWarnings.forEach((w) => {
      report += `   ⚠️  Flow "${w.flowName}" step ${w.stepOrder}: node "${w.missingNode}" not found\n`;
    });
    report += "\n";
  }

  // — Flow symbol drift (advisory) —
  const flowSymbolWarnings = result.flowSymbolWarnings || [];
  if (flowSymbolWarnings.length > 0) {
    report += `⚠️  FLOW SYMBOL WARNINGS: ${flowSymbolWarnings.length} (advisory, flowSymbolCheck)\n`;
    flowSymbolWarnings.slice(0, 10).forEach((w) => {
      report += `   • flow "${w.flowId}" step ${w.stepOrder} (${w.node}): "${w.symbol}" not found in node's files\n`;
    });
    if (flowSymbolWarnings.length > 10) {
      report += `   ... and ${flowSymbolWarnings.length - 10} more\n`;
    }
    report += "\n";
  }

  // — Curated content lint —
  const contentViolations = result.contentViolations || [];
  if (contentViolations.length > 0) {
    report += `🚫 CURATED CONTENT VIOLATIONS: ${contentViolations.length}\n`;
    report += "   Stale terms found in hand-authored prose. Fix the data files by hand:\n";
    contentViolations.forEach((v) => {
      report += `   • ${v.kind} "${v.target}": contains "${v.phrase}"\n`;
      report += `       ${v.reason}\n`;
    });
    report += "\n";
  }

  // — File changes —
  report += "═══════════════════════════════════════════════════════════\n";
  if (result.hasChanges) {
    report += "📝 FILES WRITTEN:\n";
    if (result.nodesChanged) report += "   • data/nodes.js (updated)\n";
    if (result.edgesChanged) report += "   • data/edges.js (updated)\n";
    report += "   • architecture.json (regenerated)\n";
    report += "   • architecture.html (regenerated)\n";
    report += "   • ARCHITECTURE.md (regenerated)\n";
    report += "   • ARCHITECTURE_CHARTS.md (regenerated)\n";
    report += "\n";
    if (contentViolations.length > 0) {
      report += "💥 GOVERNANCE CHECK FAILED — curated prose references stale terms.\n";
      report +=
        "   The engine will not auto-edit prose; fix data/nodes.js, data/edges.js, or data/flows.js.\n";
    } else if (result.flowWarnings.length > 0) {
      report += "💥 GOVERNANCE CHECK FAILED — flows.js references missing nodes.\n";
      report += "   flows.js is curated: fix the node references by hand; a re-run will not clear this.\n";
    } else if (result.strictLocalFail) {
      report += "💥 GOVERNANCE CHECK FAILED — strictUnmappedLocal: local files are imported\n";
      report += "   but not covered by nodeMapping. Add mappings for the files listed above.\n";
    } else {
      report += "💥 GOVERNANCE CHECK FAILED — data was corrected from codebase.\n";
      report += "   Run again to verify idempotence (should exit 0 on re-run).\n";
    }
  } else {
    report += "✅ GOVERNANCE CHECK PASSED — architecture graph matches codebase.\n";
    report += "   No changes needed. All nodes and edges verified.\n";
    report += "   • ARCHITECTURE.md and ARCHITECTURE_CHARTS.md are up to date.\n";
  }

  return report;
}

// Total governance verdict: any node/edge/pattern delta, flow warning, stale
// metadata path, or on-disk artifact drift must fail the build (exit 1).
function computeExitCode(result, changedPaths) {
  return result.hasChanges || changedPaths.length > 0;
}

module.exports = {
  orderNodes,
  renderArchitectureMd,
  renderChartsMd,
  renderHtml,
  renderReport,
  computeExitCode,
};
